sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: g4X1MUtN7rUg8nbwI2gWflk/Mv4RWOEFFCaNz0mz3CwMnKU9K1ysRygC81DFraq2K15jcb/ype1Wa+bEkTwH19qMyUlnfl3BaFut/PUyK9SSVki4Mwbxv6OMSjSOZ/xcPVfDkKZGN8KwNLo9f9dqInlnejnlGVzlaVppq4wcwMjfyR/BCUK+aTE8ZPUfRnzEhHG8rzOuKQ1bhxNJWNF1fUR0B+FRRedxKJLk8xTtNP+G44x5V+sIBUOsy4UAwksI6UFJwuyLMUpaISYQ1wmTgCWJ03BDBvpjFpE6tj33KedbEGpOeJKHNs805BP6tlxn7omuf5XXwq0fDRyyIuY7I6JK/k4EmUX6ZWxlbl8qPi76ofPfZHBolUJhNNj4tHfPt9YonqmRIgjkkEZy2+M1n8Y83qCwhP9YaQCZmQbDUvRe6nV+rIfw2Joq+wlY2Z3KnaC1KK3KhT/28zabTg0uiRgU1nq48XurKlJmUyOvGatml0WKEVm+hAd/CDDcjJ5TeJQdCnVOx1K8zgsBvoIJN5OZhV/sFmpveYC6osPZiiR5tUxI6XI88dU4/ppxDqxL/QFAjduKkRfBDJ9IXRnxZTVkFSkKibcCVbzk8e8lky9tibmFbZSmFt8q2cXZq9SerCfdBPed/H3uv+9cV6yOOwVeAz+bA6C297I04PsbtNE=
branches:
  only:
  - master
