sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.1
install:
  - bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
    - secure: Xo+tvHNJz5HrrQ7WiSj1HP7PHQaFnSYRVdNFKsDPqOQerQjuh1WHK6BYnwG3dl/0VU/6VcR8NNlwYxVhUUyfTqYQ7AqtMuGgSP/KYlYO/K7Rx/I+nQ3yiDmaahkqxeFd/FCyA3q7EMTHcbMtlIYox/yxHZ08lq7mosFeDiwB/W7038OOfooyndbQM9jFeaZko4ALmRcPzZ981mRDt14x/ydX9nANsepmPG+S4VDGSoPTNdI71J6YQBIkJTIT5MpasAkQ4sb0i/kXEK/LL98y39lVKEop37xqr1fmh+EPF3A+uU1ztxdJV3QYF16UpiOzlrsZid6okc7MDT7LUAUwLMNBjGf35+dA6sVGSxm1QXHA0APvi2QDDOuZbkhq81hLV4LG/x5A4EsxktOqjg/q2g+KJypY4BXhW2N44JYoRepn6fQOLnFd6zuzbxoW42/D7VilLEooczWpmRq44VKpErmk5DehvjhBdHR1WJA9CZbHidZt7hNPBQqlDw333jt1Zy+nrDi78P7e5KQR4qc7el4lhmzxZxyB1Oo82sh8Sj7z4WvQ1Pv5if7Xmo0WeppcNM+oVl6BMW+TkniUedAUXWvtxmW6LNEr6NRvQubMjT4KZhLpkURhfMiTFSoqeV5TNpUXRrI+jC59uAKMc+uoRlIowZfIsH486epW6U0tBUQ=
branches:
  only:
    - master
