sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.1
install:
  - bundle install
script: bundle exec rake site:deploy --quiet
branches:
  only:
    - master
env:
  global:
    - secure: SlSEatVsyNM/jB8UGMQacK0tVVxmScLJxRony23ZO0RQC8JQ4fO35f3kUgPbReviH1gnzJOGmJG9xZ2aBzGXHFUGP+1McSpwoX5oU3yKYWHBe0BAWN/g6Hmq01xAdPtL6eW5PjsqevPS0D1Y46tvteB4rOa0jD7oUxhTjhw1gM93tA82ora0e/wbJNA9ExSv9iZg5yx6Nz8eqcGuaDTUX3dkAKay92nvzLFcEN8v2NQfcehOgtBUK7NLPinVQ71jzSD+Rlbr7frFDG4WtcVx/JfXp2L5dcf+dL90UfxKeH/uabfqACzPEz6k7uH9Qw6J5qgMjEx0OyzTuMR5c69LqNHLG001MugNhYxbaizOFr2HE2TVZCJxWzv4mCL0Qu0WhsftsBi/9N/FsVnW86CkPhe8iJX2cPsLTeQM1PKdt+3QyNgBqniddVznKqD8yiGyGWYXJoUM4QKPxSEV0TNzd8TN60Yd2MBbmH5uzgYU4e4rNlcm0UinYKV6mafley2FvnD1PFib2klBkUfFbt05C8KLZo0xUVzUfOCFr17B81bAc7/lTFm5J3hKfskDWYzTbZsKCKFD0uMp0MF9eX1y0HmSgA2WsBHCQvZljhV5VZM70kAI+UpClc3Wyq7shNxxIPjHA+7sOBnQUUmYkDOH593FZIjEM6AtdYTFhg0reVk=
