# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 100 # it will paginate after this number
language: "en-uk"
words_per_minute: 200

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: "/"

# Website info
title: America's Water Blog
description: An inclusive online community reimagining infrastructure design and water management in the farms, cities, and watercourses of the future
cover: assets/images/blog-cover.jpg
favicon: assets/images/favicon.ico
CNAME: americaswater.blog

# Social info
email: jdossgollin.psu@gmail.com # email to contact
twitter: False # replace by your username
facebook: False # replace by your username

navigation: False # show the navbar links
subscribers: False # you need to connect an external service for this to work,
# if 'True' the submit button is disabled for now, but you can change that
# by editing `_includes/subscribe-form.html`

# Permalinks
permalink: /:title
# permalink: /author/:author
# permalink: /tag/:tag

# Authors' info in `_data/authors.yml`
# Tags' info in `_data/tags_info.yml`

# gems and other configs
plugins_dir: "_plugins"
plugins:
  - jekyll-feed
  - jekyll-katex
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-scholar

relative_links:
  enabled: true
  collections: false

feed:
  path: feed.xml

# Settings for deploy rake task
safe: False
lsi: False
username: jdossgollin
repo: americas-water-blog
branch: master
destination: _site
production_url: https://americaswater.blog
source_url: https://github.com/jdossgollin/americas-water-blog/

# have to add this or else jekyll won't build the pages here
include: [_pages]

# To use Utterance comments,  you can going to https://utteranc.es/ get more parameters interpretation.
utterance:
  repo: jdossgollin/americas-water-blog
  issue-term: title # Choose the mapping between blog posts and GitHub issues.
  theme: github-light # Choose an Utterances theme that matches your blog. 'github-light' is default
  label: blog-comments # Choose the label that will be assigned to issues created by Utterances.

# settings for jeykll-scholar
scholar:
  style: american-geophysical-union
  source: ./_bibliography
  bibliography: library.bib
  sort_by: year
  order: descending

# these files will be ignored by jekyll when building the website
exclude:
  - .git*
  - .travis.yml
  - "*.Rmd"
  - assets/css
  - changelog.md
  - Gemfile
  - Gemfile.lock
  - GHOST.txt
  - gulpfile.js
  - LICENSE
  - node_modules
  - Rakefile
  - README.md
  - script.py
  - vendor
