# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 100 # it will paginate after this number
language: "en-uk"
words_per_minute: 200

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: "/"

# Website info
title: America's Water Blog
description: An inclusive online community working towards equitable, sustainable, and resilient water systems
cover: assets/images/blog-cover.jpg
#logo: assets/images/blog-icon.png
#logo_dark: assets/images/favicon.png
favicon: assets/images/favicon.png
CNAME: americaswater.blog

# Social info
email: jdossgollin.psu@gmail.com # email to contact
twitter: False # replace by your username
facebook: False # replace by your username

navigation: False # show the navbar links
subscribers: False # you need to connect an external service for this to work,
# if 'True' the submit button is disabled for now, but you can change that
# by editing `_includes/subscribe-form.html`

# Permalinks
permalink: /:title
# permalink: /author/:author
# permalink: /tag/:tag

# Authors' info in `_data/authors.yml`
# Tags' info in `_data/tags_info.yml`

# gems and other configs
plugins_dir: [_plugins]
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: false

feed:
  path: feed.xml

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: False
lsi: False
username: jdossgollin
repo: americas-water-blog
branch: master
destination: _site
production_url: https://americaswater.blog
source_url: https://github.com/jdossgollin/americas-water-blog/

include: [_pages]

# To use Utterance comments,  you can going to https://utteranc.es/ get more parameters interpretation.
utterance:
  repo: jdossgollin/americas-water-blog
  issue-term: title # Choose the mapping between blog posts and GitHub issues.
  theme: github-light # Choose an Utterances theme that matches your blog. 'github-light' is default
  label: blog-comments # Choose the label that will be assigned to issues created by Utterances.

exclude:
  - assets/css
  - node_modules
  - vendor
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - GHOST.txt
  - gulpfile.js
  - LICENSE
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - script.py
  - changelog.md
  - "*.Rmd"
  - .git*
